site_name: LIBXSMM
site_author: Hans Pabst
copyright: Copyright (c) 2009-2018, LIBXSMM <a href="http://libxsmm.readthedocs.io/LICENSE/">Contributors</a>.
site_description: Library targeting Intel Architecture for specialized dense and sparse matrix operations, and deep learning primitives.
repo_url: https://github.com/hfp/libxsmm/
edit_uri: edit/master/documentation
docs_dir: documentation

markdown_extensions:
- toc:
    permalink: True
    title: None
extra_css:
- style.css

theme:
    name: readthedocs
    custom_dir: .theme
theme_dir: .theme

pages:
- Overview: index.md
- Domains:
  - "MM: Matrix Multiplication": libxsmm_mm.md
  - "DNN: Deep Neural Networks": libxsmm_dl.md
  - "AUX: Service Functions": libxsmm_aux.md
  - "PROF: Performance Profiling": libxsmm_prof.md
  - "TUNE: Customization": libxsmm_tune.md
  - "BE: Backend": libxsmm_be.md
- Samples: libxsmm_samples.md
- Applications:
  - CP2K Molecular Dynamics: cp2k.md
  - GxM Deeplearning: gxm.md
  - TensorFlow Serving: tfserving.md
  - TensorFlow: tensorflow.md
- About:
  - Contributing: CONTRIBUTING.md
  - License: LICENSE.md
